[package]
name = "bovey-program-memory"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
num-traits = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[target.'cfg(target_os = "bovey")'.dependencies]
bovey-define-syscall = { workspace = true }

[lints]
workspace = true
