[package]
name = "bovey-shred-version"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bovey-hard-forks = { workspace = true }
bovey-hash = { workspace = true }
bovey-sha256-hasher = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
