[package]
name = "bovey-feature-gate-interface"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-account = { workspace = true, optional = true }
bovey-account-info = { workspace = true, optional = true }
bovey-instruction = { workspace = true, optional = true }
bovey-program-error = { workspace = true, optional = true }
bovey-pubkey = { workspace = true }
bovey-rent = { workspace = true, optional = true }
bovey-sdk-ids = { workspace = true }
bovey-system-interface = { workspace = true, optional = true, features = [
    "bincode",
] }

[dev-dependencies]
bovey-feature-gate-interface = { path = ".", features = ["dev-context-only-utils"] }

[features]
bincode = [
    "dep:bincode",
    "dep:bovey-account",
    "dep:bovey-account-info",
    "dep:bovey-instruction",
    "dep:bovey-program-error",
    "dep:bovey-rent",
    "dep:bovey-system-interface",
    "serde"
]
dev-context-only-utils = ["bincode"]
serde = ["dep:serde", "dep:serde_derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
