[package]
name = "bovey-atomic-u64"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[target.'cfg(not(target_pointer_width = "64"))'.dependencies]
parking_lot = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
