[package]
name = "bovey-decode-error"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
num-traits = { workspace = true }

[dev-dependencies]
num-derive = { workspace = true }
