[package]
name = "bovey-signature"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bs58 = { workspace = true }
ed25519-dalek = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde-big-array = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-sanitize = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
bs58 = { workspace = true, features = ["std"] }
curve25519-dalek = { workspace = true }
ed25519-dalek = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
bovey-pubkey = { workspace = true, features = ["std"] }
bovey-short-vec = { workspace = true }
bovey-signature = { path = ".", features = ["serde"] }

[features]
default = ["std"]
frozen-abi = [
    "dep:bovey-frozen-abi",
    "dep:bovey-frozen-abi-macro",
    "std"
]
rand = ["dep:rand"]
serde = ["dep:serde", "dep:serde_derive", "dep:serde-big-array"]
std = []
verify = ["dep:ed25519-dalek"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lints]
workspace = true
