[package]
name = "bovey-bucket-map"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bv = { workspace = true, features = ["serde"] }
bytemuck = { workspace = true }
bytemuck_derive = { workspace = true }
log = { workspace = true }
memmap2 = { workspace = true }
modular-bitfield = { workspace = true }
num_enum = { workspace = true }
rand = { workspace = true }
bovey-clock = { workspace = true }
bovey-measure = { workspace = true }
bovey-pubkey = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
fs_extra = { workspace = true }
rayon = { workspace = true }
bovey-logger = { workspace = true }
bovey-pubkey = { workspace = true, features = ["rand"] }

[lib]
crate-type = ["lib"]
name = "bovey_bucket_map"
