[package]
name = "ocp-config-program"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
serde = { workspace = true }
serde_derive = { workspace = true }
bovey-account = { workspace = true }
bovey-bincode = { workspace = true }
bovey-instruction = { workspace = true }
bovey-log-collector = { workspace = true }
bovey-packet = { workspace = true }
bovey-program-runtime = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-sdk-ids = { workspace = true }
bovey-short-vec = { workspace = true }
bovey-stake-interface = { workspace = true }
bovey-system-interface = { workspace = true }
bovey-transaction-context = { workspace = true }

[dev-dependencies]
bovey-keypair = { workspace = true }
bovey-logger = { workspace = true }
bovey-signer = { workspace = true }

[lib]
crate-type = ["lib"]
name = "ocp_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
