[package]
name = "bovey-example-mocks"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
serde_derive = { workspace = true }
bovey-address-lookup-table-interface = { workspace = true }
bovey-clock = { workspace = true }
bovey-hash = { workspace = true }
bovey-instruction = { workspace = true }
bovey-keccak-hasher = { workspace = true }
bovey-message = { workspace = true, features = ["serde"] }
bovey-nonce = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-sdk-ids = { workspace = true }
bovey-system-interface = { workspace = true }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
