[package]
name = "bovey-seed-phrase"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
hmac = { workspace = true }
pbkdf2 = { workspace = true }
sha2 = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
