[package]
name = "bovey-program-error"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
borsh = { workspace = true, optional = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-decode-error = { workspace = true }
bovey-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
bovey-msg = { workspace = true }
bovey-pubkey = { workspace = true, default-features = false }

[features]
borsh = ["dep:borsh"]
serde = ["dep:serde", "dep:serde_derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
