[package]
name = "ocp-associated-token-account"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
borsh = "1.5.5"
num-derive = "0.4"
num-traits = "0.2"
bovey-program = { workspace = true }
ocp-associated-token-account-client = { workspace = true }
ocp-token = { workspace = true, features = ["no-entrypoint"] }
ocp-token-2022 = { workspace = true, features = ["no-entrypoint"] }
thiserror = "2.0"

[dev-dependencies]
bovey-program-test = { workspace = true }
bovey-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
