[package]
name = "bovey-loader-v3-interface"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-frozen-abi = { workspace = true, features = [
    "frozen-abi",
], optional = true }
bovey-frozen-abi-macro = { workspace = true, features = [
    "frozen-abi",
], optional = true }
bovey-instruction = { workspace = true, features = ["std"] }
bovey-pubkey = { workspace = true, features = ["curve25519"] }
bovey-sdk-ids = { workspace = true }
bovey-system-interface = { workspace = true, features = ["bincode"], optional = true }

[dev-dependencies]
bincode = { workspace = true }
bovey-loader-v3-interface = { path = ".", features = ["dev-context-only-utils"] }

[features]
bincode = ["dep:bovey-system-interface", "serde", "bovey-instruction/bincode"]
dev-context-only-utils = ["bincode"]
frozen-abi = ["dep:bovey-frozen-abi", "dep:bovey-frozen-abi-macro", "serde"]
serde = ["dep:serde", "dep:serde_bytes", "dep:serde_derive", "bovey-pubkey/serde"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lints]
workspace = true
