[package]
name = "bovey-poseidon"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }

[target.'cfg(target_os = "bovey")'.dependencies]
bovey-define-syscall = { workspace = true }

[target.'cfg(not(target_os = "bovey"))'.dependencies]
ark-bn254 = { workspace = true }
light-poseidon = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
