[package]
name = "bovey-program-entrypoint"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bovey-account-info = { workspace = true }
bovey-msg = { workspace = true }
bovey-program-error = { workspace = true }
bovey-pubkey = { workspace = true, default-features = false }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
