[package]
name = "ocp-pod"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
serde-traits = ["dep:serde"]
borsh = ["dep:borsh"]

[dependencies]
borsh = { version = "1.5.5", optional = true }
bytemuck = { version = "1.21.0" }
bytemuck_derive = { version = "1.8.1" }
num-derive = "0.4"
num-traits = "0.2"
serde = { version = "1.0.217", optional = true }
bovey-decode-error = { workspace = true }
bovey-msg = { workspace = true }
bovey-program-error = { workspace = true }
bovey-program-option = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-zk-sdk = { workspace = true }
thiserror = "2.0"

[dev-dependencies]
serde_json = "1.0.138"
base64 = { version = "0.22.1" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
