[package]
name = "bovey-transaction-status-client-types"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
bovey-account-decoder-client-types = { workspace = true }
bovey-commitment-config = { workspace = true }
bovey-message = { workspace = true }
bovey-reward-info = { workspace = true, features = ["serde"] }
bovey-signature = { workspace = true }
bovey-transaction = { workspace = true, features = ["serde"] }
bovey-transaction-context = { workspace = true }
bovey-transaction-error = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
