[package]
name = "bovey-epoch-rewards-hasher"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
siphasher = { workspace = true }
bovey-hash = { workspace = true }
bovey-pubkey = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
