[package]
name = "ocp-bpf-loader-program"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bincode = { workspace = true }
libsecp256k1 = { workspace = true }
qualifier_attr = { workspace = true }
scopeguard = { workspace = true }
bovey-account = { workspace = true }
bovey-account-info = { workspace = true }
bovey-big-mod-exp = { workspace = true }
bovey-bincode = { workspace = true }
bovey-blake3-hasher = { workspace = true }
bovey-bn254 = { workspace = true }
bovey-clock = { workspace = true }
bovey-compute-budget = { workspace = true }
bovey-cpi = { workspace = true }
bovey-curve25519 = { workspace = true }
bovey-feature-set = { workspace = true }
bovey-hash = { workspace = true }
bovey-instruction = { workspace = true }
bovey-keccak-hasher = { workspace = true }
bovey-loader-v3-interface = { workspace = true, features = ["serde"] }
bovey-loader-v4-interface = { workspace = true, features = ["bincode"] }
bovey-log-collector = { workspace = true }
bovey-measure = { workspace = true }
bovey-packet = { workspace = true }
bovey-poseidon = { workspace = true }
bovey-precompiles = { workspace = true }
bovey-program-entrypoint = { workspace = true }
bovey-program-memory = { workspace = true }
bovey-program-runtime = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-bpf = { workspace = true }
bovey-sdk-ids = { workspace = true }
bovey-secp256k1-recover = { workspace = true }
bovey-sha256-hasher = { workspace = true }
bovey-stable-layout = { workspace = true }
bovey-system-interface = { workspace = true }
bovey-sysvar = { workspace = true }
bovey-sysvar-id = { workspace = true }
bovey-timings = { workspace = true }
bovey-transaction-context = { workspace = true, features = ["bincode"] }
bovey-type-overrides = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }
ocp-bpf-loader-program = { path = ".", features = ["vm-internal"] }
bovey-epoch-rewards = { workspace = true }
bovey-epoch-schedule = { workspace = true }
bovey-fee-calculator = { workspace = true }
bovey-last-restart-slot = { workspace = true }
bovey-program = { workspace = true }
bovey-pubkey = { workspace = true, features = ["rand"] }
bovey-rent = { workspace = true }
bovey-slot-hashes = { workspace = true }
bovey-transaction-context = { workspace = true, features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }
test-case = { workspace = true }

[lib]
crate-type = ["lib"]
name = "ocp_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["metrics"]
metrics = ["bovey-program-runtime/metrics"]
shuttle-test = [
    "bovey-type-overrides/shuttle-test",
    "bovey-program-runtime/shuttle-test",
    "bovey-bpf/shuttle-test"
]
vm-internal = []
