[package]
name = "ocp-associated-token-account-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bovey-instruction = { workspace = true, features = ["std"] }
bovey-pubkey = { workspace = true, features = ["curve25519"] }

[dev-dependencies]
bovey-program = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
