[package]
name = "ocp-program-error"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
num-derive = "0.4"
num-traits = "0.2"
bovey-program = { workspace = true }
ocp-program-error-derive = { workspace = true }
thiserror = "2.0"

[dev-dependencies]
lazy_static = "1.5"
serial_test = "3.2"
bovey-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
