[package]
name = "bovey-serde-varint"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
rand = { workspace = true }
serde_derive = { workspace = true }
bovey-short-vec = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
