[package]
name = "bovey-feature-set"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
ahash = { workspace = true }
lazy_static = { workspace = true }
bovey-epoch-schedule = { workspace = true }
bovey-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-hash = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-sha256-hasher = { workspace = true }

[features]
frozen-abi = ["dep:bovey-frozen-abi", "dep:bovey-frozen-abi-macro"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
