[package]
name = "bovey-rent-collector"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-account = { workspace = true }
bovey-clock = { workspace = true }
bovey-epoch-schedule = { workspace = true }
bovey-frozen-abi = { workspace = true, optional = true }
bovey-frozen-abi-macro = { workspace = true, optional = true }
bovey-genesis-config = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-rent = { workspace = true }
bovey-sdk-ids = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bovey-logger = { workspace = true }
bovey-pubkey = { workspace = true, features = ["rand"] }

[features]
frozen-abi = ["dep:bovey-frozen-abi", "dep:bovey-frozen-abi-macro"]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "bovey-epoch-schedule/serde",
    "bovey-rent/serde",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lints]
workspace = true
