[package]
name = "bovey-pubsub-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
bovey-account-decoder-client-types = { workspace = true }
bovey-clock = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-rpc-client-api = { workspace = true }
bovey-signature = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"] }
url = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
bovey-commitment-config = { workspace = true }
bovey-pubkey = { workspace = true, features = ["rand"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
