[package]
name = "bovey-client-traits"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bovey-account = { workspace = true }
bovey-commitment-config = { workspace = true }
bovey-epoch-info = { workspace = true }
bovey-hash = { workspace = true }
bovey-instruction = { workspace = true }
bovey-keypair = { workspace = true }
bovey-message = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-signature = { workspace = true }
bovey-signer = { workspace = true }
bovey-system-interface = { workspace = true }
bovey-transaction = { workspace = true, features = ["bincode"] }
bovey-transaction-error = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
