[package]
name = "bovey-version"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
semver = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
bovey-feature-set = { workspace = true }
bovey-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-sanitize = { workspace = true }
bovey-serde-varint = { workspace = true }

[features]
dummy-for-ci-check = []
frozen-abi = [
    "dep:bovey-frozen-abi",
    "dep:bovey-frozen-abi-macro",
]

[lib]
name = "bovey_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
