[package]
name = "bovey-fee"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bovey-feature-set = { workspace = true }
bovey-fee-structure = { workspace = true }
bovey-vm-transaction = { workspace = true }
