[package]
name = "bovey-transaction-error"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-frozen-abi = { workspace = true, optional = true }
bovey-frozen-abi-macro = { workspace = true, optional = true }
bovey-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
bovey-sanitize = { workspace = true }

[features]
frozen-abi = ["dep:bovey-frozen-abi", "dep:bovey-frozen-abi-macro"]
serde = ["dep:serde", "dep:serde_derive", "bovey-instruction/serde"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lints]
workspace = true
