[package]
name = "bovey-clap-v3-utils"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true, features = ["default"] }
clap = { version = "3.2.23", features = ["cargo"] }
rpassword = { workspace = true }
bovey-clock = { workspace = true }
bovey-cluster-type = { workspace = true }
bovey-commitment-config = { workspace = true }
bovey-derivation-path = { workspace = true }
# the borsh feature is required to use the value_parser macro
bovey-hash = { workspace = true, features = ["borsh"] }
bovey-keypair = { workspace = true, features = ["seed-derivable"] }
bovey-message = { workspace = true }
bovey-native-token = { workspace = true }
bovey-presigner = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-remote-wallet = { workspace = true, features = ["default"] }
bovey-seed-derivable = { workspace = true }
bovey-seed-phrase = { workspace = true }
bovey-signature = { workspace = true }
bovey-signer = { workspace = true }
bovey-zk-token-sdk = { workspace = true }
thiserror = { workspace = true }
tiny-bip39 = { workspace = true }
uriparse = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bovey-pubkey = { workspace = true, features = ["rand"] }
bovey-system-interface = { workspace = true, features = ["bincode"] }
tempfile = { workspace = true }

[lib]
name = "bovey_clap_v3_utils"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
