[package]
name = "bovey-fee-structure"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-native-token = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[target.'cfg(not(target_os = "bovey"))'.dependencies]
bovey-message = { workspace = true }

[features]
frozen-abi = ["dep:bovey-frozen-abi"]
serde = ["dep:serde", "dep:serde_derive"]

[lints]
workspace = true
