[package]
name = "ocp-token-confidential-transfer-proof-generation"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
curve25519-dalek = "4.1.3"
bovey-zk-sdk = { workspace = true }
thiserror = "2.0.11"

[lints]
workspace = true
