[package]
name = "bovey-bincode"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
bovey-instruction = { workspace = true, default-features = false, features = [
    "std",
] }

[dev-dependencies]
bovey-system-interface = { workspace = true, features = ["bincode"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
