[package]
name = "bovey-big-mod-exp"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[target.'cfg(target_os = "bovey")'.dependencies]
bovey-define-syscall = { workspace = true }

[target.'cfg(not(target_os = "bovey"))'.dependencies]
num-bigint = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
array-bytes = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
