[package]
name = "bovey-compute-budget-instruction"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
bovey-borsh = { workspace = true }
bovey-builtins-default-costs = { workspace = true, features = ["vm-internal"] }
bovey-compute-budget = { workspace = true }
bovey-compute-budget-interface = { workspace = true, features = ["borsh"] }
bovey-feature-set = { workspace = true }
bovey-instruction = { workspace = true }
bovey-packet = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-sdk-ids = { workspace = true }
bovey-vm-transaction = { workspace = true }
bovey-transaction-error = { workspace = true }
thiserror = { workspace = true }

[lib]
crate-type = ["lib"]
name = "bovey_compute_budget_instruction"

[dev-dependencies]
bincode = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }
bovey-builtins-default-costs = { workspace = true, features = ["dev-context-only-utils", "vm-internal"] }
bovey-hash = { workspace = true }
bovey-keypair = { workspace = true }
bovey-message = { workspace = true }
bovey-program = { workspace = true }
bovey-signer = { workspace = true }
bovey-system-interface = { workspace = true }
bovey-transaction = { workspace = true, features = ["blake3"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
dev-context-only-utils = []

[lints]
workspace = true
