[package]
name = "ocp-address-lookup-table-program"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bincode = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
bovey-address-lookup-table-interface = { workspace = true, features = [
    "bincode",
    "bytemuck",
] }
bovey-feature-set = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_os = "bovey"))'.dependencies]
bovey-bincode = { workspace = true }
bovey-clock = { workspace = true }
bovey-instruction = { workspace = true }
bovey-log-collector = { workspace = true }
bovey-packet = { workspace = true }
bovey-program-runtime = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-system-interface = { workspace = true, features = ["bincode"] }
bovey-transaction-context = { workspace = true, features = ["bincode"] }

[lib]
crate-type = ["lib"]
name = "ocp_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
