[package]
name = "bovey-keccak-hasher"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
borsh = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
bovey-hash = { workspace = true }
bovey-sanitize = { workspace = true }

[target.'cfg(not(target_os = "bovey"))'.dependencies]
sha3 = { workspace = true }

[target.'cfg(target_os = "bovey")'.dependencies]
# sha3 should be removed in the next breaking release,
# as there's no reason to use the crate instead of the syscall
# onchain
sha3 = { workspace = true, optional = true }
bovey-define-syscall = { workspace = true }

[features]
borsh = ["dep:borsh", "std"]
frozen-abi = ["dep:bovey-frozen-abi", "dep:bovey-frozen-abi-macro", "std"]
serde = ["dep:serde", "dep:serde_derive"]
sha3 = ["dep:sha3"]
std = ["bovey-hash/std"]

[lints]
workspace = true
