[package]
name = "bovey-epoch-schedule"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-frozen-abi = { workspace = true, optional = true }
bovey-frozen-abi-macro = { workspace = true, optional = true }
bovey-sdk-ids = { workspace = true, optional = true }
bovey-sdk-macro = { workspace = true }
bovey-sysvar-id = { workspace = true, optional = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
bovey-clock = { workspace = true }
bovey-epoch-schedule = { path = ".", features = ["sysvar"] }
static_assertions = { workspace = true }

[features]
frozen-abi = ["dep:bovey-frozen-abi", "dep:bovey-frozen-abi-macro"]
serde = ["dep:serde", "dep:serde_derive"]
sysvar = ["dep:bovey-sdk-ids", "dep:bovey-sysvar-id"]

[lints]
workspace = true
