[package]
name = "bovey-define-syscall"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_feature, values("static-syscalls"))',
] }
