[package]
name = "bovey-inline-ocp"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { workspace = true }
bovey-pubkey = { workspace = true, features = ["bytemuck"] }

[lib]
crate-type = ["lib"]
name = "bovey_inline_ocp"

[dev-dependencies]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
