[package]
name = "bovey-cpi"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bovey-account-info = { workspace = true }
bovey-instruction = { workspace = true }
bovey-program-error = { workspace = true }
bovey-pubkey = { workspace = true }

[target.'cfg(target_os = "bovey")'.dependencies]
bovey-define-syscall = { workspace = true }
bovey-stable-layout = { workspace = true }

[dev-dependencies]
bovey-program-entrypoint = { workspace = true }
bovey-pubkey = { workspace = true, features = ["curve25519"] }
bovey-sdk-ids = { workspace = true }
bovey-system-interface = { workspace = true, features = ["bincode"] }
static_assertions = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
