[package]
name = "bovey-serialize-utils"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bovey-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
bovey-pubkey = { workspace = true, default-features = false }
bovey-sanitize = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
borsh = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
bovey-pubkey = { workspace = true, default-features = false, features = [
    "borsh",
    "serde",
] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
