[package]
name = "bovey-slot-hashes"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-hash = { workspace = true, default-features = false }
bovey-sdk-ids = { workspace = true, optional = true }
bovey-sysvar-id = { workspace = true, optional = true }

[dev-dependencies]
bovey-sha256-hasher = { workspace = true }

[features]
serde = ["dep:serde", "dep:serde_derive", "bovey-hash/serde"]
sysvar = ["dep:bovey-sdk-ids", "dep:bovey-sysvar-id"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
