[package]
name = "ocp-compute-budget-program"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
qualifier_attr = { workspace = true }
bovey-program-runtime = { workspace = true }

[lib]
crate-type = ["lib"]
name = "ocp_compute_budget_program"

[features]
vm-internal = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
