[package]
name = "bovey-system-transaction"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bovey-hash = { workspace = true }
bovey-keypair = { workspace = true }
bovey-message = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-signer = { workspace = true }
bovey-system-interface = { workspace = true, features = ["bincode"] }
bovey-transaction = { workspace = true, features = ["bincode"] }
