[package]
name = "bovey-sha256-hasher"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bovey-hash = { workspace = true }

[target.'cfg(not(target_os = "bovey"))'.dependencies]
sha2 = { workspace = true }

[target.'cfg(target_os = "bovey")'.dependencies]
# sha2 should be removed in the next breaking release,
# as there's no reason to use the crate instead of the syscall
# onchain
sha2 = { workspace = true, optional = true }
bovey-define-syscall = { workspace = true }

[features]
sha2 = ["dep:sha2"]

[lints]
workspace = true
