[package]
name = "ocp-token-group-interface"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bytemuck = "1.20.0"
num-derive = "0.4"
num-traits = "0.2"
bovey-decode-error = { workspace = true }
bovey-instruction = { workspace = true }
bovey-msg = { workspace = true }
bovey-program-error = { workspace = true }
bovey-pubkey = { workspace = true }
ocp-discriminator = { workspace = true }
ocp-pod = { workspace = true, features = ["borsh"] }
thiserror = "2.0"

[dev-dependencies]
bovey-sha256-hasher = { workspace = true }
ocp-type-length-value = { workspace = true, features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
