[package]
name = "bovey-metrics"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
gethostname = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
bovey-clock = { workspace = true }
bovey-cluster-type = { workspace = true }
bovey-sha256-hasher = { workspace = true }
bovey-time-utils = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
rand = { workspace = true }
serial_test = { workspace = true }

[lib]
name = "bovey_metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
