[package]
name = "bovey-account-info"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
bovey-program-error = { workspace = true }
bovey-program-memory = { workspace = true }
bovey-pubkey = { workspace = true, default-features = false }

[features]
bincode = ["dep:bincode", "dep:serde"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
