[package]
name = "bovey-transaction-metrics-tracker"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
# Update this borsh dependency to the workspace version once
lazy_static = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
bovey-packet = { workspace = true }
bovey-perf = { workspace = true }
bovey-short-vec = { workspace = true }
bovey-signature = { workspace = true }

[dev-dependencies]
bovey-hash = { workspace = true }
bovey-keypair = { workspace = true }
bovey-pubkey = { workspace = true, features = ["rand"] }
bovey-system-transaction = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
