[package]
name = "bovey-keygen"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bs58 = { workspace = true }
clap = { version = "3.1.5", features = ["cargo"] }
dirs-next = { workspace = true }
num_cpus = { workspace = true }
serde_json = { workspace = true }
bovey-clap-v3-utils = { workspace = true }
bovey-cli-config = { workspace = true }
bovey-derivation-path = { workspace = true }
bovey-instruction = { workspace = true }
bovey-keypair = { workspace = true }
bovey-message = { workspace = true, features = ["bincode"] }
bovey-pubkey = { workspace = true }
bovey-remote-wallet = { workspace = true, features = ["default"] }
bovey-seed-derivable = { workspace = true }
bovey-signer = { workspace = true }
bovey-version = { workspace = true }
tiny-bip39 = { workspace = true }

[dev-dependencies]
bovey-pubkey = { workspace = true, features = ["rand"] }
tempfile = { workspace = true }

[[bin]]
name = "bovey-keygen"
path = "src/keygen.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
