[package]
name = "bovey-keypair"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bs58 = { workspace = true, features = ["std"] }
ed25519-dalek = { workspace = true }
ed25519-dalek-bip32 = { workspace = true, optional = true }
rand0-7 = { workspace = true }
bovey-derivation-path = { workspace = true, optional = true }
bovey-pubkey = { workspace = true }
bovey-seed-derivable = { workspace = true, optional = true }
bovey-seed-phrase = { workspace = true }
bovey-signature = { workspace = true, features = ["verify"] }
bovey-signer = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
static_assertions = { workspace = true }
tiny-bip39 = { workspace = true }

[features]
seed-derivable = ["dep:bovey-derivation-path", "dep:bovey-seed-derivable", "dep:ed25519-dalek-bip32"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
