[package]
name = "bovey-tps-client"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
bovey-account = { workspace = true }
bovey-client = { workspace = true }
bovey-client-traits = { workspace = true, optional = true }
bovey-clock = { workspace = true }
bovey-commitment-config = { workspace = true }
bovey-connection-cache = { workspace = true }
bovey-epoch-info = { workspace = true }
bovey-hash = { workspace = true }
bovey-keypair = { workspace = true }
bovey-message = { workspace = true }
bovey-pubkey = { workspace = true }
bovey-quic-client = { workspace = true }
bovey-rpc-client = { workspace = true }
bovey-rpc-client-api = { workspace = true }
bovey-runtime = { workspace = true, optional = true }
bovey-signature = { workspace = true }
bovey-signer = { workspace = true }
bovey-streamer = { workspace = true }
bovey-tpu-client = { workspace = true }
bovey-transaction = { workspace = true }
bovey-transaction-error = { workspace = true }
bovey-transaction-status = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bovey-runtime = { workspace = true, features = ["dev-context-only-utils"] }
tempfile = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bank-client = ["dep:bovey-client-traits", "dep:bovey-runtime"]
