[package]
name = "bovey-presigner"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bovey-pubkey = { workspace = true }
bovey-signature = { workspace = true, features = ["verify"] }
bovey-signer = { workspace = true }

[dev-dependencies]
bovey-keypair = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
