[package]
name = "bovey-vm-rent-collector"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bovey-sdk = { workspace = true }
