[package]
name = "bovey-fee-calculator"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
log = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
bovey-frozen-abi = { workspace = true, optional = true }
bovey-frozen-abi-macro = { workspace = true, optional = true }

[dev-dependencies]
bovey-clock = { workspace = true }
bovey-logger = { workspace = true }
static_assertions = { workspace = true }

[features]
frozen-abi = ["dep:bovey-frozen-abi", "dep:bovey-frozen-abi-macro"]
serde = ["dep:serde", "dep:serde_derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]
